---
info:
  title: lwm2m_firmware_update_attributes
attributes:
  - name: lwm2m_fup_pkg_name
    required: true
    schema:
      maxLength: 32
      minLength: 1
      type: string
    x-ctype: string
    x-broadcast: true
    x-default: my_firmware
    x-prepare: false
    x-readable: true
    x-savable: false
    x-writable: false
    summary: Firmware update firmware package name
  - name: lwm2m_fup_pkg_ver
    required: true
    schema:
      maxLength: 32
      type: string
    x-ctype: string
    x-broadcast: true
    x-default: 0.0.0
    x-prepare: false
    x-readable: true
    x-savable: false
    x-writable: false
    summary: Firmware update package version
  - name: lwm2m_fup_proxy_srv
    required: true
    schema:
      maxLength: 255
      minLength: 11 # coap://1.io
      type: string
      pattern: ^coaps?://[a-zA-Z0-9]+(-[a-zA-Z0-9]+)?(\.[a-zA-Z0-9]+(-[a-zA-Z0-9]+)?)+(:\d{1,5})?/?$
    x-ctype: string
    x-broadcast: true
    x-default: coaps://coap-proxy.salticidae.net:5684
    x-prepare: false
    x-readable: true
    x-savable: true
    x-writable: true
    summary: Firmware update proxy server
